services:
  db:
    image: postgres:16-alpine
    container_name: ucode_db
    environment:
      POSTGRES_USER: ucode
      POSTGRES_PASSWORD: ucode
      POSTGRES_DB: ucode
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nginx_network

  backend:
    container_name: ucode_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:5001
    expose:
      - "5001"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
    name: nginx_network

volumes:
  db_data:
